source 'https://rubygems.org'

# The ARM64 ffi package requires Ruby 3 or newer.
ruby '>= 3.0.0'

gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
gem 'cocoapods', '1.17.0'
gem 'ffi', '1.17.4'
gem 'xcpretty', '0.3.0'
