name: Setup
description: Set up the repository Node.js toolchain and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: .nvmrc
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
